language: go

sudo: required

services:
  - docker

go:
- 1.8
- 1.9

cache:
  directories:
  - vendor

before_install:
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/golang/lint/golint

install:
- make dep

script:
- make cover

after_success:
- bash <(curl -s https://codecov.io/bash)
